name: 'Get latest Github release'
description: 'Get the latest release from another repository and output that for use in other actions'

inputs:
  token:
    description: 'GitHub Access token'
    required: false
  repository:
    description: 'The repository name in full formar (owner/repo)'
    required: true
  type:
    description: 'Wanted release type (latest, stable, draft, nodraft)'
    required: true
  package:
    description: 'Monorepo package name'
    required: true

outputs:
  release:
    description: 'Release tag'
  release_id:
    description: 'Release Github ID'
  browser_download_url:
    description: 'Release first asset download URL'

runs:
  using: 'docker'
  image: 'Dockerfile'