name: 'Get latest Github release'
description: 'Get the latest release from another repository and output that for use in other actions'
author: "rez0n"

branding:
  icon: 'anchor'
  color: 'orange'

inputs:
  token:
    description: 'GitHub Access token'
    required: false
  repository:
    description: 'The repository name in full formar (owner/repo)'
    required: true
  type:
    description: 'Wanted release type (latest, stable, draft, nodraft)'
    required: true

outputs:
  release:
    description: 'Release tag'
  release_id:
    description: 'Release Github ID'
  browser_download_url:
    description: 'Release first asset download URL'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    # use the input if provided, otherwise use values from the env
    token: ${{ inputs.token || env.token }}
    repository: ${{ inputs.repository || env.repository }}
    type: ${{ inputs.type || env.type }}
